name: Trigger auto deployment for new-horizon-cont-backend-ai-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      branches: [ main ]
    pull_request:
      branches: [ "main" ]
    paths:
    - 'src/**'
    - '.github/workflows/new-horizon-cont-backend-ai-app-AutoDeployTrigger-f01288c4-622a-4732-b46f-bc94c104ba08.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: newhorizoncontregistry.azurecr.io
          username: ${{ secrets.NEWHORIZONCONTBACKENDAIAPP_REGISTRY_USERNAME }}
          password: ${{ secrets.NEWHORIZONCONTBACKENDAIAPP_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: newhorizoncontregistry.azurecr.io/new-horizon-cont-backend-ai-app:${{ github.sha }}
          file: ./src/Dockerfile
          context: ./src/


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.NEWHORIZONCONTBACKENDAIAPP_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n new-horizon-cont-backend-ai-app -g new-horizon-rg --server newhorizoncontregistry.azurecr.io --username  ${{ secrets.NEWHORIZONCONTBACKENDAIAPP_REGISTRY_USERNAME }} --password ${{ secrets.NEWHORIZONCONTBACKENDAIAPP_REGISTRY_PASSWORD }}
            az containerapp update -n new-horizon-cont-backend-ai-app -g new-horizon-rg --image newhorizoncontregistry.azurecr.io/new-horizon-cont-backend-ai-app:${{ github.sha }}
